### ISSUE TITLE
Toolbar button is inserted after url bar in Firefox Developer Edition

### ISSUE THREAD

**Issue by Keith94** [kashiif/copy-urls-expert#38]
## Steps to reproduce

1. Install and launch [Firefox Developer Edition](https://www.mozilla.org/firefox/developer/)
2. Install Copy Urls Expert and restart

## Expected result
CUE toolbar button is appended at the rightmost position in the toolbar

## Actual result
CUE toolbar button is appended after the url bar by default

![firefox_2017-01-25_07-53-00](https://cloud.githubusercontent.com/assets/5490615/22298544/b790e022-e2d5-11e6-98fb-e02ac4899f61.png)

**Comment by kashiif** [comment]
This is by design. If the button has to be added, it should be visible immediately after install. If the user has a few buttons in toolbar already, the button will hide in menu panel. (Think about a user installing the extension for first time, they would "complain" there is no toolbar button as claimed on AMO page)

**Comment by kashiif** [comment]
I can change it so it appears after the search bar. Thoughts?

**Comment by Keith94** [comment]
redacted
